version: '3'

services:
  magento:
    image: bitnami/magento:2.4.6
    container_name: magento
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      MAGENTO_USERNAME: admin
      MAGENTO_PASSWORD: parcelpro1
      MAGENTO_HOST: localhost
      MAGENTO_DATABASE_HOST: db
      MAGENTO_DATABASE_PORT_NUMBER: 3306
      MAGENTO_DATABASE_USER: magento
      MAGENTO_DATABASE_PASSWORD: magento
      MAGENTO_DATABASE_NAME: magento
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT_NUMBER: 9200
      ALLOW_EMPTY_PASSWORD: yes
      BITNAMI_DEBUG: true
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - db
      - elasticsearch
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_USER: magento
      MARIADB_PASSWORD: magento
      MARIADB_DATABASE: magento
    volumes:
      - 'db_data:/var/lib/mysql'
  elasticsearch:
    # TODO: Can we use the official elasticsearch image instead of a bitnami one?
    image: bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'

volumes:
  magento_data:
    driver: local
  db_data:
    driver: local
  elasticsearch_data:
    driver: local
